[package]
name = "dmux"
version = "0.4.1"
authors = ["Zachary Thomas <zdcthomas@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tmux_interface = "0.0.6"
clap = "~2.27.0"
dirs = "2.0.2"
walkdir = "2"
url = '2.1.1'
regex = '1.3.7'
config = '0.10.1'
serde = "1.0"
serde_derive = "1.0"
